import random
letters=["a" , "b" , "c" , "d" , "e" , "f" , "g" , "h" , "i" , "j" , "k" , "l" , "m" , "n" , "o" , "p" , "q" , "r" , "s" , "t" , "u" , "v" , "w" , "x" , "y" , "z" , "#" , "!" , "@" , "$" , "*"]
p1 = random.choice(letters)
p2 = random.choice(letters)
p3 = random.choice(letters)
p4 = random.choice(letters)
p5 = random.choice(letters)
p6 = random.choice(letters)
p7 = random.choice(letters)
p8 = random.choice(letters)
p9 = random.choice(letters)
p10 = random.choice(letters)
p11 = random.choice(letters)
p12 = random.choice(letters)
p13 = random.choice(letters)
p14 = random.choice(letters)
p15 = random.choice(letters)
p16 = random.choice(letters)
print("generating strong 8-digit password")
print(f"your 8 digit password is: {p1}{p2}{p3}{p4}{p5}{p6}{p7}{p8}")
print("generating your strong 16-digit password!")
print(f"your 16 digit password is: {p1}{p2}{p3}{p4}{p5}{p6}{p7}{p8}{p9}{p10}{p11}{p12}{p13}{p14}{p15}{p16}")
input("\nPress Enter to exit...")